### ISSUE TITLE
how Change style or css of RasterLayer ? 

### ISSUE THREAD

**Issue by sedghian** [CartoDB/mobile-android-samples#11]
hi . i use carto sdk mobile and want to change style or css of Layers by hardcode . 
how do it ? 
my code is : 
`HTTPTileDataSource http = new HTTPTileDataSource(1,19,url); `    
 `RasterTileLayer wmsLayer = new RasterTileLayer(http);`
 `mapView.getLayers().add(wmsLayer);
`

Thank you for answer .

**Comment by mtehver** [comment]
Closing this, it was answered in mobile sdk repo already.
