### ISSUE TITLE
error when trying to build with current ndk version

### ISSUE THREAD

**Issue by rexfordnyrk** [CartoDB/mobile-android-samples#8]
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

**Comment by mtehver** [comment]
Correct, we have deliberately dropped MIPS binaries to make the SDK binary smaller. To my knowledge, there are virtually no MIPS-based Android devices. Can you elaborate why you need MIPS target?

**Comment by rexfordnyrk** [comment]
well not really needed tho but I was just updating the gradle version and that error seemed to pop up frequently but fixed it. it was a gradle dependency issue.
